# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog do Everson
email: marceloeverson.rm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este blog foi criado para compartilhar conhecimentos e experiências com 
  linguagens e tecnologias de desenvolvimento e web e afins.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://marceloeverson.github.io" # the base hostname & protocol for your site
twitter_username: eversonmarcelo
github_username:  marceloeverson
gems: [jekyll-paginate]
paginate: 3
paginate_path: "/page:num/"
permalink: none

# Build settings

markdown: kramdown
# app vars
app_host: http://marceloeverson.github.io
component:
 bootstrap_css: /components/bootstrap/dist/css/bootstrap.min.css
 bootstrap_js: /components/bootstrap/dist/js/bootstrap.min.js
cdn:
   font_awesome: https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css
   bootstrap_css: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css
   bootstrap_js: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js
   lunr: //cdnjs.cloudflare.com/ajax/libs/lunr.js/0.3.3/lunr.min.js
   jquery: //cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js
   
menu_categories:
  linguagem:  ['php','javascript','css','sql']     
  biblioteca: ['jquery','undescore']
  framework: ['zend','phalcon']

    
     

